/**
 * `cognit completion <shell>` — print shell completion scripts (D-M2-02).
 *
 * Emits a static script for fish, bash, or zsh that completes Cognit
 * public verbs and common global flags. Install one-liners live in the
 * README; this command only prints to stdout.
 */
import { Command } from "commander";
import { failUsage } from "../exit.js";

/** Public + commonly used verbs users and agents type most. */
const COMMANDS = [
  "init",
  "observation",
  "observe",
  "decision",
  "verification",
  "verify",
  "conclusion",
  "continue",
  "search",
  "doctor",
  "dashboard",
  "export",
  "import",
  "reset",
  "config",
  "env",
  "session",
  "inbox",
  "completion",
  "help",
] as const;

const GLOBAL_FLAGS = ["--json", "--internal", "--root", "--help", "--version"] as const;

function fishScript(): string {
  const cmds = COMMANDS.join(" ");
  const flags = GLOBAL_FLAGS.map((f) => {
    if (f === "--root") {
      return `complete -c cognit -l root -d 'project root' -r`;
    }
    const long = f.slice(2);
    return `complete -c cognit -l ${long} -d '${long}'`;
  }).join("\n");
  return `# cognit fish completion — generated by \`cognit completion fish\`
complete -c cognit -f
complete -c cognit -n '__fish_use_subcommand' -a '${cmds}'
${flags}
complete -c cognit -n '__fish_seen_subcommand_from completion' -a 'fish bash zsh' -d 'shell'
`;
}

function bashScript(): string {
  const cmds = COMMANDS.join(" ");
  const flags = GLOBAL_FLAGS.join(" ");
  return `# cognit bash completion — generated by \`cognit completion bash\`
_cognit_completions() {
  local cur="\${COMP_WORDS[COMP_CWORD]}"
  local prev="\${COMP_WORDS[COMP_CWORD-1]}"
  if [[ "\$prev" == "--root" ]]; then
    COMPREPLY=( \$(compgen -d -- "\$cur") )
    return
  fi
  if [[ "\$cur" == -* ]]; then
    COMPREPLY=( \$(compgen -W "${flags}" -- "\$cur") )
    return
  fi
  if [[ \$COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( \$(compgen -W "${cmds}" -- "\$cur") )
    return
  fi
  if [[ "\${COMP_WORDS[1]}" == "completion" && \$COMP_CWORD -eq 2 ]]; then
    COMPREPLY=( \$(compgen -W "fish bash zsh" -- "\$cur") )
  fi
}
complete -F _cognit_completions cognit
`;
}

function zshScript(): string {
  const cmds = COMMANDS.map((c) => `'${c}'`).join(" ");
  return `# cognit zsh completion — generated by \`cognit completion zsh\`
#compdef cognit
_cognit() {
  local -a commands
  commands=(${cmds})
  local -a globals
  globals=(
    '--json[emit JSON envelope on stdout]'
    '--internal[reveal internal commands]'
    '--root[project root]:path:_files -/'
    '--help[show help]'
    '--version[show version]'
  )
  _arguments -C \\
    '1:command:->cmds' \\
    '*::arg:->args' \\
    \$globals
  case \$state in
    cmds) _describe -t commands 'cognit command' commands ;;
    args)
      if [[ \$words[1] == completion ]]; then
        _values 'shell' fish bash zsh
      fi
      ;;
  esac
}
compdef _cognit cognit
`;
}

export function registerCompletion(program: Command): void {
  program
    .command("completion")
    .description("print shell completion script for fish, bash, or zsh")
    .argument("<shell>", "target shell: fish | bash | zsh")
    .action((shell: string) => {
      const s = shell.trim().toLowerCase();
      let script: string | undefined;
      if (s === "fish") script = fishScript();
      else if (s === "bash") script = bashScript();
      else if (s === "zsh") script = zshScript();
      else {
        failUsage(`unknown shell "${shell}" (expected fish, bash, or zsh)`);
        return;
      }
      process.stdout.write(script);
    });
}
