#!/usr/bin/env node
/**
 * docker/seed-demo.mjs — Phase 6.8 one-shot demo seeder.
 *
 * Idempotent. Runs inside the server container as the first step of
 * `command:` in docker-compose.yml. On a fresh `cognit-data` volume
 * it bootstraps the DB and inserts a "Demo: HMR memory leak
 * investigation" session. On every subsequent run it sees the demo
 * session and exits 0 without touching the data.
 *
 * Self-contained: no @cognit/db, no tsx, no shell-out. Direct
 * better-sqlite3 + inline DDL. The runtime image only ships
 * better-sqlite3 (and its native binding) — bundling @/db into the
 * seed would double the image size for what is a one-line
 * "if exists skip" check.
 *
 * Schema sources: packages/db/src/schema/tables.ts (TABLES_DDL) +
 * packages/db/src/schema/migrations/0002_payload_v1.1.0.sql. The
 * strings are duplicated here on purpose: the seed must not import
 * the @/db source, and the alternative (shipping a .sql file + a
 * loader) is more moving parts than the demo data warrants.
 *
 * Idempotency rule: a single `SELECT id FROM sessions WHERE goal = ?`
 * guards the whole insert block. If that returns any row we exit 0.
 */
import Database from "better-sqlite3";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const ROOT = process.env.COGNIT_ROOT ?? "/data";
const COGNIT_DIR = path.join(ROOT, ".cognit");
const DB_PATH = path.join(COGNIT_DIR, "cognit.db");
const YAML_PATH = path.join(COGNIT_DIR, "cognit.yaml");
const GITIGNORE_PATH = path.join(COGNIT_DIR, ".gitignore");
const DEMO_GOAL = "Demo: HMR memory leak investigation";
const PROJECT_NAME = "cognit-demo";

const log = (msg) => process.stdout.write(`[seed] ${msg}\n`);

// Minimal ULID (Crockford base32, 26 chars, ms-precise timestamp +
// 80 bits of randomness). Matches the wire shape @/db emits. Avoids
// pulling the `ulid` workspace dep into the runtime image.
const ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
const ENCODE_LEN = 10;
const encodeTime = (time) => {
  let out = "";
  for (let i = ENCODE_LEN - 1; i >= 0; i--) {
    const mod = time % 32;
    out = ALPHABET[mod] + out;
    time = (time - mod) / 32;
  }
  return out;
};
const encodeRandom = () => {
  const bytes = crypto.randomBytes(10);
  let out = "";
  for (let i = 0; i < 16; i++) {
    out += ALPHABET[bytes[i] & 0x1f];
  }
  return out;
};
const ulid = () => encodeTime(Date.now()) + encodeRandom();

// ---------------------------------------------------------------------------
// 1. Filesystem: ensure .cognit/ + subdirs + cognit.yaml + .gitignore.
// ---------------------------------------------------------------------------
fs.mkdirSync(COGNIT_DIR, { recursive: true });
for (const sub of ["artifacts", "blobs", "inbox", "logs", "sessions", "snapshots"]) {
  fs.mkdirSync(path.join(COGNIT_DIR, sub), { recursive: true });
}

if (!fs.existsSync(YAML_PATH)) {
  const yaml = `# .cognit/cognit.yaml — generated by docker/seed-demo.mjs.
# Minimal config for the dockerised demo. Local-only tool — no
# auth, no API token. The server binds 0.0.0.0 inside the docker
# network but the port is never published to the host.
project: ${PROJECT_NAME}
session:
  snapshot_every_n_events: 100
  fork_on_resume: true
redaction:
  patterns: []
`;
  fs.writeFileSync(YAML_PATH, yaml, "utf8");
  log(`wrote ${YAML_PATH}`);
}

if (!fs.existsSync(GITIGNORE_PATH)) {
  fs.writeFileSync(
    GITIGNORE_PATH,
    "cognit.db\ncognit.db-shm\ncognit.db-wal\nartifacts/\nblobs/\ninbox/\nlogs/\nsessions/\nsnapshots/\n",
    "utf8",
  );
  log(`wrote ${GITIGNORE_PATH}`);
}

// ---------------------------------------------------------------------------
// 2. Open DB, apply PRAGMAS, create schema, run v1.1.0 migration.
// ---------------------------------------------------------------------------
const db = new Database(DB_PATH);
const PRAGMAS = [
  "PRAGMA journal_mode = WAL",
  "PRAGMA synchronous = NORMAL",
  "PRAGMA foreign_keys = ON",
  "PRAGMA busy_timeout = 5000",
];
for (const p of PRAGMAS) db.exec(p);

const TABLES_DDL = [
  `CREATE TABLE IF NOT EXISTS projects (
     id TEXT PRIMARY KEY,
     name TEXT NOT NULL,
     repo_url TEXT,
     created_at TEXT NOT NULL
   )`,
  `CREATE TABLE IF NOT EXISTS sessions (
     id TEXT PRIMARY KEY,
     project_id TEXT NOT NULL REFERENCES projects(id),
     parent_session_id TEXT REFERENCES sessions(id),
     goal TEXT NOT NULL,
     status TEXT NOT NULL CHECK (status IN ('active','paused','closed')),
     last_snapshot_event_id TEXT REFERENCES events(id),
     created_at TEXT NOT NULL,
     closed_at TEXT
   )`,
  `CREATE TABLE IF NOT EXISTS actors (
     id TEXT PRIMARY KEY,
     type TEXT NOT NULL CHECK (type IN ('human','worker','system')),
     name TEXT UNIQUE NOT NULL,
     trust_score REAL NOT NULL DEFAULT 0,
     first_seen_at TEXT NOT NULL,
     last_seen_at TEXT NOT NULL,
     config_json TEXT
   )`,
  `CREATE TABLE IF NOT EXISTS events (
     id TEXT PRIMARY KEY,
     project_id TEXT NOT NULL REFERENCES projects(id),
     session_id TEXT NOT NULL REFERENCES sessions(id),
     actor_id TEXT NOT NULL REFERENCES actors(id),
     type TEXT NOT NULL,
     version TEXT NOT NULL DEFAULT '1.0.0',
     payload_json TEXT NOT NULL,
     source_json TEXT,
     artifact_refs_json TEXT,
     causation_id TEXT REFERENCES events(id),
     correlation_id TEXT,
     confidence REAL,
     parent_verification_id TEXT REFERENCES events(id),
     linked_hypothesis_id TEXT REFERENCES hypotheses(id),
     created_at TEXT NOT NULL
   )`,
  `CREATE INDEX IF NOT EXISTS idx_events_session_created
     ON events(session_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_events_project_type_created
     ON events(project_id, type, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_events_actor_created
     ON events(actor_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_events_linked_hyp
     ON events(linked_hypothesis_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS snapshots (
     id TEXT PRIMARY KEY,
     session_id TEXT NOT NULL REFERENCES sessions(id),
     event_id TEXT NOT NULL REFERENCES events(id),
     state_json TEXT NOT NULL,
     event_count INTEGER NOT NULL,
     created_at TEXT NOT NULL
   )`,
  `CREATE TABLE IF NOT EXISTS artifacts (
     id TEXT PRIMARY KEY,
     session_id TEXT NOT NULL REFERENCES sessions(id),
     path TEXT NOT NULL,
     kind TEXT NOT NULL,
     sha256 TEXT NOT NULL,
     size_bytes INTEGER,
     archived_at TEXT,
     created_at TEXT NOT NULL
   )`,
  `CREATE TABLE IF NOT EXISTS edges (
     id TEXT PRIMARY KEY,
     session_id TEXT NOT NULL REFERENCES sessions(id),
     edge_type TEXT NOT NULL,
     from_entity_type TEXT NOT NULL,
     from_entity_id TEXT NOT NULL,
     to_entity_type TEXT NOT NULL,
     to_entity_id TEXT NOT NULL,
     created_at TEXT NOT NULL
   )`,
  `CREATE INDEX IF NOT EXISTS idx_edges_session ON edges(session_id)`,
  `CREATE INDEX IF NOT EXISTS idx_edges_from ON edges(from_entity_type, from_entity_id)`,
  `CREATE INDEX IF NOT EXISTS idx_edges_to ON edges(to_entity_type, to_entity_id)`,
  `CREATE TABLE IF NOT EXISTS constraint_rules (
     id TEXT PRIMARY KEY,
     condition_json TEXT NOT NULL,
     actions_json TEXT NOT NULL,
     enabled INTEGER DEFAULT 1,
     created_at TEXT NOT NULL
   )`,
  `CREATE TABLE IF NOT EXISTS schema_version (
     id INTEGER PRIMARY KEY CHECK (id = 1),
     version TEXT NOT NULL,
     applied_at TEXT NOT NULL
   )`,
  `CREATE TABLE IF NOT EXISTS hypotheses (
     id TEXT PRIMARY KEY,
     session_id TEXT NOT NULL REFERENCES sessions(id),
     title TEXT NOT NULL,
     text TEXT NOT NULL,
     status TEXT NOT NULL CHECK (status IN ('active','weakened','rejected','promoted')),
     created_at TEXT NOT NULL
   )`,
  `CREATE TABLE IF NOT EXISTS inbox_processed (
     id TEXT PRIMARY KEY,
     file TEXT NOT NULL,
     processed_at TEXT NOT NULL
   )`,
];
for (const ddl of TABLES_DDL) db.exec(ddl);

// v1.1.0 migration. The migration runner in @/db tracks applied
// versions in `schema_version`; we replicate the same bookkeeping
// here so the live server (which reads `events.stdout_excerpt` etc.)
// can boot.
const MIGRATION_0002_SQL = `
ALTER TABLE events ADD COLUMN stdout_excerpt TEXT;
ALTER TABLE events ADD COLUMN exit_code INTEGER;
ALTER TABLE events ADD COLUMN duration_ms INTEGER;
ALTER TABLE events ADD COLUMN created_artifact_id TEXT REFERENCES artifacts(id);
CREATE INDEX IF NOT EXISTS idx_artifacts_archived ON artifacts(archived_at);
`;
db.exec("CREATE TABLE IF NOT EXISTS schema_version (id INTEGER PRIMARY KEY CHECK (id = 1), version TEXT NOT NULL, applied_at TEXT NOT NULL)");
const sv = db.prepare("SELECT version FROM schema_version WHERE id = 1").get();
if (!sv) {
  const ts = new Date().toISOString();
  db.exec(MIGRATION_0002_SQL);
  db.prepare("INSERT INTO schema_version (id, version, applied_at) VALUES (1, '1.1.0', ?)").run(ts);
  log("applied migration 1.1.0");
}

// ---------------------------------------------------------------------------
// 3. Idempotent project + actor bootstrap.
// ---------------------------------------------------------------------------
const ensureProject = db.prepare(
  `INSERT INTO projects (id, name, repo_url, created_at) VALUES (?, ?, NULL, ?)
   ON CONFLICT(id) DO NOTHING`,
);
const findProjectByName = db.prepare(`SELECT * FROM projects WHERE name = ? ORDER BY created_at ASC, id ASC LIMIT 1`);
let project = findProjectByName.get(PROJECT_NAME);
if (!project) {
  const id = ulid();
  ensureProject.run(id, PROJECT_NAME, new Date().toISOString());
  project = db.prepare(`SELECT * FROM projects WHERE id = ?`).get(id);
  log(`created project ${PROJECT_NAME} (${id})`);
}

const ensureActor = (name, type, trust) => {
  const existing = db.prepare(`SELECT * FROM actors WHERE name = ?`).get(name);
  if (existing) return existing;
  const id = ulid();
  const ts = new Date().toISOString();
  db.prepare(
    `INSERT INTO actors (id, type, name, trust_score, first_seen_at, last_seen_at, config_json)
     VALUES (?, ?, ?, ?, ?, ?, NULL)`,
  ).run(id, type, name, trust, ts, ts);
  log(`registered actor ${name} (${type})`);
  return db.prepare(`SELECT * FROM actors WHERE id = ?`).get(id);
};

const worker = ensureActor("claude-seed", "worker", 0.7);
const human = ensureActor("seed", "human", 1.0);
const system = ensureActor("cognit-system", "system", 0.5);

// ---------------------------------------------------------------------------
// 4. Idempotency check on the demo session.
// ---------------------------------------------------------------------------
const existingDemo = db.prepare(`SELECT id FROM sessions WHERE goal = ?`).get(DEMO_GOAL);
if (existingDemo) {
  log(`demo session already present (id=${existingDemo.id}); nothing to do`);
  db.close();
  process.exit(0);
}

// ---------------------------------------------------------------------------
// 5. Insert the demo session + 7 events.
// ---------------------------------------------------------------------------
const sessionId = ulid();
const sessionTs = new Date().toISOString();

db.exec("BEGIN");
try {
  db.prepare(
    `INSERT INTO sessions (id, project_id, parent_session_id, goal, status, last_snapshot_event_id, created_at, closed_at)
     VALUES (?, ?, NULL, ?, 'active', NULL, ?, NULL)`,
  ).run(sessionId, project.id, DEMO_GOAL, sessionTs);

  // session_created event
  const sessionCreatedId = ulid();
  db.prepare(
    `INSERT INTO events (id, project_id, session_id, actor_id, type, version, payload_json, source_json, artifact_refs_json,
                         causation_id, correlation_id, confidence, parent_verification_id, linked_hypothesis_id, created_at)
     VALUES (?, ?, ?, ?, 'session_created', '1.1.0', ?, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ?)`,
  ).run(
    sessionCreatedId,
    project.id,
    sessionId,
    system.id,
    JSON.stringify({ goal: DEMO_GOAL, parent_session_id: null }),
    sessionTs,
  );

  // observation_recorded
  const obsId = ulid();
  db.prepare(
    `INSERT INTO events (id, project_id, session_id, actor_id, type, version, payload_json, source_json, artifact_refs_json,
                         causation_id, correlation_id, confidence, parent_verification_id, linked_hypothesis_id, created_at)
     VALUES (?, ?, ?, ?, 'observation_recorded', '1.1.0', ?, NULL, NULL, NULL, NULL, 0.9, NULL, NULL, ?)`,
  ).run(
    obsId,
    project.id,
    sessionId,
    worker.id,
    JSON.stringify({ text: "Next.js dev server reaches 18GB VmPeak after 30 minutes of editing." }),
    new Date().toISOString(),
  );

  // finding_created
  const findingId = ulid();
  db.prepare(
    `INSERT INTO events (id, project_id, session_id, actor_id, type, version, payload_json, source_json, artifact_refs_json,
                         causation_id, correlation_id, confidence, parent_verification_id, linked_hypothesis_id, created_at)
     VALUES (?, ?, ?, ?, 'finding_created', '1.1.0', ?, NULL, NULL, NULL, NULL, 0.85, NULL, NULL, ?)`,
  ).run(
    findingId,
    project.id,
    sessionId,
    worker.id,
    JSON.stringify({
      text: "Memory growth correlates with HMR rebuilds, not request count.",
      related_observation_ids: [obsId],
    }),
    new Date().toISOString(),
  );

  // theory_created
  const theoryId = ulid();
  db.prepare(
    `INSERT INTO events (id, project_id, session_id, actor_id, type, version, payload_json, source_json, artifact_refs_json,
                         causation_id, correlation_id, confidence, parent_verification_id, linked_hypothesis_id, created_at)
     VALUES (?, ?, ?, ?, 'theory_created', '1.1.0', ?, NULL, NULL, NULL, NULL, 0.7, NULL, NULL, ?)`,
  ).run(
    theoryId,
    project.id,
    sessionId,
    worker.id,
    JSON.stringify({
      title: "HMR module graph listener retention",
      text: "Each HMR rebuild retains module-graph listeners because dev-server shutdown never reaps the previous graph.",
    }),
    new Date().toISOString(),
  );

  // hypothesis_created (linked to the theory via parent linkage in event payload + linkedHypothesisId)
  const hypId = ulid();
  db.prepare(
    `INSERT INTO events (id, project_id, session_id, actor_id, type, version, payload_json, source_json, artifact_refs_json,
                         causation_id, correlation_id, confidence, parent_verification_id, linked_hypothesis_id, created_at)
     VALUES (?, ?, ?, ?, 'hypothesis_created', '1.1.0', ?, NULL, NULL, NULL, NULL, 0.65, NULL, NULL, ?)`,
  ).run(
    hypId,
    project.id,
    sessionId,
    worker.id,
    JSON.stringify({
      title: "Module graph leak in HMR runtime",
      text: "When the dev server processes a HMR update it constructs a fresh module graph but never drops the previous one.",
    }),
    new Date().toISOString(),
  );
  // Backfill the hypotheses table row so the dashboard's reducer view resolves the entity.
  db.prepare(
    `INSERT INTO hypotheses (id, session_id, title, text, status, created_at) VALUES (?, ?, ?, ?, 'active', ?)`,
  ).run(hypId, sessionId, "Module graph leak in HMR runtime", "When the dev server processes a HMR update it constructs a fresh module graph but never drops the previous one.", new Date().toISOString());

  // verification_started
  const verStartedId = ulid();
  db.prepare(
    `INSERT INTO events (id, project_id, session_id, actor_id, type, version, payload_json, source_json, artifact_refs_json,
                         causation_id, correlation_id, confidence, parent_verification_id, linked_hypothesis_id, created_at)
     VALUES (?, ?, ?, ?, 'verification_started', '1.1.0', ?, NULL, NULL, NULL, NULL, NULL, NULL, ?, ?)`,
  ).run(
    verStartedId,
    project.id,
    sessionId,
    worker.id,
    JSON.stringify({ command: "node -e \"console.log('hold 1s')\"", type: "exec", linked_hypothesis_id: hypId, expected_duration_ms: 1500 }),
    hypId,
    new Date().toISOString(),
  );

  // verification_passed (with v1.1.0 outcome fields)
  const verPassedId = ulid();
  db.prepare(
    `INSERT INTO events (id, project_id, session_id, actor_id, type, version, payload_json, source_json, artifact_refs_json,
                         causation_id, correlation_id, confidence, parent_verification_id, linked_hypothesis_id, created_at,
                         stdout_excerpt, exit_code, duration_ms, created_artifact_id)
     VALUES (?, ?, ?, ?, 'verification_passed', '1.1.0', ?, NULL, NULL, ?, NULL, NULL, ?, NULL, ?,
             'hold 1s', 0, 1023, NULL)`,
  ).run(
    verPassedId,
    project.id,
    sessionId,
    worker.id,
    JSON.stringify({ exit_code: 0, duration_ms: 1023, stdout_excerpt: "hold 1s", created_artifact_id: null }),
    verStartedId,
    verStartedId,
    new Date().toISOString(),
  );

  // conclusion_proposed
  const conclId = ulid();
  db.prepare(
    `INSERT INTO events (id, project_id, session_id, actor_id, type, version, payload_json, source_json, artifact_refs_json,
                         causation_id, correlation_id, confidence, parent_verification_id, linked_hypothesis_id, created_at)
     VALUES (?, ?, ?, ?, 'conclusion_proposed', '1.1.0', ?, NULL, NULL, NULL, NULL, 0.8, NULL, ?, ?)`,
  ).run(
    conclId,
    project.id,
    sessionId,
    human.id,
    JSON.stringify({ text: "HMR module graph leaks ~5MB per rebuild, reproducible on long-running dev sessions." }),
    hypId,
    new Date().toISOString(),
  );

  // conclusion_verified
  db.prepare(
    `INSERT INTO events (id, project_id, session_id, actor_id, type, version, payload_json, source_json, artifact_refs_json,
                         causation_id, correlation_id, confidence, parent_verification_id, linked_hypothesis_id, created_at)
     VALUES (?, ?, ?, ?, 'conclusion_verified', '1.1.0', ?, NULL, NULL, NULL, NULL, 0.85, NULL, NULL, ?)`,
  ).run(
    ulid(),
    project.id,
    sessionId,
    human.id,
    JSON.stringify({ verification_id: verPassedId, supporting_evidence_ids: [obsId, findingId] }),
    new Date().toISOString(),
  );

  // decision_proposed
  const decId = ulid();
  db.prepare(
    `INSERT INTO events (id, project_id, session_id, actor_id, type, version, payload_json, source_json, artifact_refs_json,
                         causation_id, correlation_id, confidence, parent_verification_id, linked_hypothesis_id, created_at)
     VALUES (?, ?, ?, ?, 'decision_proposed', '1.1.0', ?, NULL, NULL, NULL, NULL, 0.75, NULL, NULL, ?)`,
  ).run(
    decId,
    project.id,
    sessionId,
    human.id,
    JSON.stringify({ text: "Disable HMR in CI builds and on long-running dev sessions.", based_on_conclusion_ids: [conclId] }),
    new Date().toISOString(),
  );

  // decision_accepted
  db.prepare(
    `INSERT INTO events (id, project_id, session_id, actor_id, type, version, payload_json, source_json, artifact_refs_json,
                         causation_id, correlation_id, confidence, parent_verification_id, linked_hypothesis_id, created_at)
     VALUES (?, ?, ?, ?, 'decision_accepted', '1.1.0', ?, NULL, NULL, NULL, NULL, 0.85, NULL, NULL, ?)`,
  ).run(
    ulid(),
    project.id,
    sessionId,
    human.id,
    JSON.stringify({ based_on_conclusion_ids: [conclId] }),
    new Date().toISOString(),
  );

  // schema_version row
  db.exec("COMMIT");
  log(`seeded demo session ${sessionId} with 11 events`);
} catch (e) {
  db.exec("ROLLBACK");
  console.error("[seed] failed:", e);
  db.close();
  process.exit(1);
}

db.close();
